repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/pycqa/isort
  rev: 5.11.4
  hooks:
  - id: isort
    args: [--force-single-line-imports]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: [--extend-ignore=E501]

- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    args: [--line-length=160]
